name: blendjam
description: 30 Song Auto DJ Mixer for Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.42
  file_picker: ^5.5.0
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
