name: blendjam
description: BlendJam DJ Mixer - Real Audio Blending
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.10.6
  just_audio_background: ^0.0.4
  audio_waveforms: ^1.0.6
  file_picker: ^10.2.0
  ffmpeg_kit_flutter: ^6.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
