buildscript {
    ext {
        compileSdkVersion = 36
        targetSdkVersion = 36
        minSdkVersion = 23
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.0"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
    
    // NUCLEAR OPTION: Force every plugin to use 36
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 36
                buildToolsVersion "36.0.0"
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
