include ':app'

def flutterProjectRoot = new File(settingsDir.toFile(), "..").getAbsolutePath()
def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot, '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = new File(path)
    if (!pluginDirectory.exists()) {
        throw new GradleException("Flutter plugin $name not found at $path")
    }
    apply from: "$pluginDirectory/android/include.gradle"
}
