android {
    namespace "com.pmakpah.blendjam"
    compileSdkVersion 36
    buildToolsVersion "36.0.0"
    ndkVersion "26.1.10909125"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    defaultConfig {
        applicationId "com.pmakpah.blendjam"
        minSdkVersion 23 // <- ffmpeg_kit needs 23
        targetSdkVersion 36
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
